# Site settings
title: "Bewerbung"
email: annika.hamachers@uni-muenster.de
description: "Bewerbung um eine wissenschaftliche Projektstelle."
baseurl: "/Bewerbung2CarteNoire/"
url: "http://brigitbardot.github.io"
title_description: "Bewerbungstext"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
post_limit: 5

# Social usernames/URLs
twitter_username: nikaOk85
github_username:  BriGitBardot
linkedin_link: https://www.linkedin.com/profile/preview?vpa=pub&locale=de_DE
stackoverflow_link: http://stackoverflow.com/users/3616812/user3616812

# Footer
footer_right: "powered by <a href=\"https://github.com/jacobtomlinson/carte-noire\">Jekyll</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


permalink: pretty
exclude: [vendor]
